name: Build-Test

on:
  push:
    branches: "*"
    paths-ignore:
      - '**/build-release.yml'
      - 'appveyor.yml'
      - '**/README.md'
  pull_request:
    branches: "*"
    paths-ignore:
      - '**/build-release.yml'
      - 'appveyor.yml'
      - '**/README.md'


env:
  DOTNET_NOLOGO: false
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ windows-latest ]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref || github.ref_name }}
      
    - name: Get submodules
      run: |
        git config --global url."https://".insteadOf git://
        git submodule update --init --recursive
        
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9
        
    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release
